# Generated by Django 2.2.3 on 2022-04-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_author', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('O', 'Others')], max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_category', models.CharField(max_length=40, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Data_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
                ('idiom', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.TextField(blank=True, default='0 kb', null=True)),
                ('year', models.IntegerField(blank=True, default=2022, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id_sub_category', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_subcategory', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.Category')),
            ],
            options={
                'verbose_name': 'Sub_Category',
                'verbose_name_plural': 'Sub_Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cours', models.CharField(max_length=400, unique=True)),
                ('description_cours', models.TextField()),
                ('image_cours', models.ImageField(upload_to='learning')),
                ('link_cours', models.URLField()),
                ('idiom_cours', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('author_cours', models.ManyToManyField(to='Learning.Author')),
                ('subcategory', models.ManyToManyField(to='Learning.Sub_Category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['title_cours'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=250, unique=True)),
                ('description_book', models.TextField()),
                ('content_book', models.TextField()),
                ('image_book', models.ImageField(upload_to='learning')),
                ('link_book', models.URLField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('author_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.Author')),
                ('data_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Learning.Data_sheet')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.Sub_Category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
